book_list/book_api/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class BookApiForm(FlaskForm):
    search          = StringField(validators=[DataRequired()])
    submit_search   = SubmitField('Szukaj')
    submit_all      = SubmitField('Dodaj wszystkie!')

book_list/book_api/views.py
import requests
from flask import render_template, Blueprint, request, session

from book_list.book_api.forms import BookApiForm
from book_list.models import Book
from book_list import config
book_api = Blueprint('book_api', __name__)


class gbooks():
    googleapikey = config["GOOGLE_API"]["KEY"]

    def search(self, value):
        parms = {"q": value, 'key': self.googleapikey}
        r = requests.get(url="https://www.googleapis.com/books/v1/volumes", params=parms)
        rj = r.json()
        return rj["items"]


def bookDecoder(obj):
    obj = obj["volumeInfo"]

    bookdict = {
        "title"     :        obj.get('title', "Brak danych"),
        "author"    :        ','.join(obj.get('authors', [])),
        "pub_date"  :        obj.get('publishedDate', ""),
        "isbn"      :        "Brak danych",
        "link"      :        "empty",
        "lan"       :        obj.get('language', ""),
        "pages_number"     :        0,
    }
    try:
        bookdict.update({
            'isbn'  : obj['industryIdentifiers'][0]['identifier'],
        })
    except:
        pass

    try:
        bookdict.update({
            'link'  : obj["imageLinks"]["thumbnail"],
        })
    except:
        pass

    try:
        bookdict['pages_number'] = int(obj.get("pageCount",0))
    except:
        pass

    return bookdict


@book_api.route('/bookapi', methods=['GET', 'POST'])
def search():
    form = BookApiForm()
    deactivated_add = False
    books = []
    if form.validate_on_submit():
        bk = gbooks()
        result = bk.search(form.search.data)
        deactivated_add = True
        for dictbook in result:
            book = bookDecoder(dictbook)
            books.append(book)
        if form.submit_all.data:
            for el in books:
                Book(**el).save_to_db()


    session['books']           = books
    session['deactivated_add'] = deactivated_add
    return render_template('bookapi.html', form=form, books=books, deactivated=deactivated_add)


@book_api.route('/book/<string:book_id>/add', methods=['GET', 'POST'])
def add(book_id):
    if request.method == 'POST':
        for book in session.get('books', None):
            if book.get("isbn", 'default_value') == book_id:
                Book(**book).save_to_db()

    return render_template('bookapi.html',
                           form=BookApiForm(),
                           books=session.get('books', None),
                           deactivated=session.get('deactivated_add', False))

book_list/books/views.py
from flask import render_template, url_for, redirect, Blueprint, request

from book_list import db
from book_list.books.forms import BookForm
from book_list.models import Book

books = Blueprint('books', __name__)


@books.route('/add/Book', methods=['GET', 'POST'])
def add_book():
    form = BookForm()

    if form.validate_on_submit() and form.check_form():
        book = Book(
            title       = form.title.data,
            author      = form.author.data,
            pub_date    = form.pub_date.data,
            isbn        = form.isbn.data,
            link        = form.img.data,
            language    = form.lan.data,
            pages       = form.pages_number.data)
        book.save_to_db()
        # flash("Dodano książkę!")
        return redirect(url_for('core.index'))

    return render_template('addbook.html', form=form)


@books.route('/book/<int:book_id>', methods=["GET", "POST"])
def update(book_id):
    # grab the requested blog post by id number or return 404
    book = Book.query.get_or_404(book_id)
    form = BookForm()
    if form.validate_on_submit() and form.check_form():
        book.title          = form.title.data
        book.author         = form.author.data
        book.pub_date       = form.pub_date.data
        book.isbn           = form.isbn.data
        book.link           = form.img.data
        book.lan            = form.lan.data
        book.pages_number   = form.pages_number.data
        db.session.commit()
        # flash("Zmiana zatwierdzona!")
        return redirect(url_for('core.index'))
    elif request.method == 'GET':
        form.title.data         = book.title
        form.author.data        = book.author
        form.pub_date.data      = book.pub_date
        form.isbn.data          = book.isbn
        form.img.data           = book.link
        form.lan.data           = book.lan
        form.pages_number.data  = book.pages_number

    return render_template('addbook.html', form=form)


@books.route('/book/<int:book_id>/delete', methods=["POST"])
def delete(book_id):
    book = Book.query.get_or_404(book_id)

    book.delete_from_db()
    # flash('Usunięto Książkę')
    return redirect(url_for('core.index'))

book_list/core/views.py
from flask import render_template, Blueprint, redirect, request

from book_list.books.forms import SearchBookForm
from book_list.models import Book

core = Blueprint('core', __name__)


@core.route('/index')
def index_redirect():
    return redirect('/')


def search_book(i, val, books):
    switcher = {

        "title": books.filter(Book.title.like('%' + val + '%')),

        "author": books.filter(Book.author.like('%' + val + '%')),

        "lan": books.filter(Book.lan.like('%' + val + '%')),

        "all": books

    }

    return switcher.get(i, books)


@core.route('/', methods=['GET', 'POST'])
def index():
    '''
    This is the home page view. Use pagination to show
    a Book List.
    '''
    page = request.args.get('page', 1, type=int)
    books = Book.query
    searchform = SearchBookForm()
    if searchform.validate_on_submit():
        val = searchform.val.data
        name = searchform.valuesType.data
        books = search_book(name, val, books)
        if searchform.use_data.data:
            data_str = searchform.start_date.data
            data_end = searchform.end_date.data
            books = books.filter(Book.pub_date.between(data_str, data_end))

    books = books.order_by(Book.id).paginate(page=page, per_page=100)
    return render_template('index.html', books=books, searchform=searchform)

book_list/templates/addbook.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-row">
            <div class="form-group col-md-6">
                {{ wtf.form_field(form.title, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(form.author, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(form.img, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(form.lan, class="form-control") }}
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                {{ wtf.form_field(form.pub_date, class="form-control") }}
            </div>
            <div class="form-group col-md-3">
                {{ wtf.form_field(form.isbn, class="form-control") }}
            </div>
            <div class="form-group col-md-3">
                {{ wtf.form_field(form.pages_number, class="form-control") }}
            </div>
        </div>

        {{ form.submit(class="btn btn-primary") }}
    </form>
{% endblock content %}

book_list/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Book List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Job interview exercise"/>
    <meta name="language" content="Polish"/>
    <meta name="keywords" content="Job, Python, Junior"/>
    <meta name="author" content="https://github.com/markoseb"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<div class="fh5co-loader"></div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('core.index') }}">Lista Książek</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('books.add_book') }}">Dodaj Książkę<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('book_api.search') }}">Book Api<span
                        class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="help-block">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning" style="background-color: #fbf2eb;">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% block content %}

    {% endblock %}
</div>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="/static/js/tabel.js"></script>

</body>
</html>

book_list/templates/bookapi.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

    <form method="POST">
        {{ form.hidden_tag() }}

        <div class="form-group col-md-6">
            {{ wtf.form_field(form.search, class="form-control") }}
            {{ form.submit_search(class="btn btn-primary btn-xs") }}
            {% if deactivated %}
                {{ form.submit_all(class="btn btn-primary btn-xs") }}
            {% endif %}
        </div>

    </form>
    <div class="table-responsive">
        <input type="hidden" name="book" value=""/>
        <table id="bookTabel" class="table table-striped table-bordered table-sm">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tytuł</th>
                <th scope="col">Autor</th>
                <th scope="col">Data Publikacji</th>
                <th scope="col">ISBN</th>
                <th scope="col">Numer Stron</th>
                <th scope="col">Okładka</th>
                <th scope="col">Język</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for book in books %}
                <tr>
                    <th scope="row"><a>{{ book.id }}</a></th>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.pub_date }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.pages }}</td>
                    <td><a href="{{ book.link }}">link</a></td>
                    <td>{{ book.lan }}</td>
                    <td>
                        <form action="{{ url_for('book_api.add',book_id=book.isbn) }}" name="addBook" method="POST">
                            <button type="submit" class="btn btn-danger btn-sm"><i aria-hidden="true"></i>Add
                            </button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

book_list/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}


    <form method="POST">
        {{ searchform.hidden_tag() }}
        <div class="m-4 form-row">
            <div class="form-group col-md-6">
                {{ wtf.form_field(searchform.valuesType, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(searchform.val, class="form-control") }}
            </div>
            <div class="form-group col-md-12">
                {{ wtf.form_field(searchform.use_data, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(searchform.start_date, class="form-control") }}
            </div>
            <div class="form-group col-md-6">
                {{ wtf.form_field(searchform.end_date, class="form-control") }}
            </div>
            {{ searchform.submit(class="btn btn-primary") }}
        </div>

    </form>

    <div class="table-responsive">
        <table id="bookTabel" class="table table-striped table-bordered table-sm">
            <caption>Lista Książek</caption>
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Tytuł</th>
                <th scope="col">Autor</th>
                <th scope="col">Data Publikacji</th>
                <th scope="col">ISBN</th>
                <th scope="col">Numer Stron</th>
                <th scope="col">Okładka</th>
                <th scope="col">Język</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for book in books.items %}
                <tr>
                    <th scope="row"><a href="{{ url_for('books.update', book_id=book.id) }}">{{ book.id }}</a></th>
                    <td>{{ book.title }}</td>
                    <td>{{ book.author }}</td>
                    <td>{{ book.pub_date }}</td>
                    <td>{{ book.isbn }}</td>
                    <td>{{ book.pages_number }}</td>
                    <td><a href="{{ book.link }}">link</a></td>
                    <td>{{ book.lan }}</td>
                    <td>
                        <form action="{{ url_for('books.delete',book_id=book.id) }}" method="POST">
                            <button type="submit" class="btn btn-danger btn-sm"><i aria-hidden="true"></i>X</button>
                        </form>
                    </td>
                    <td>
                        <form action="{{ url_for('books.update', book_id=book.id) }}" >
                            <button type="submit" class="btn btn-primary btn-sm"><i aria-hidden="true"></i>Edit</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}